runtime: python
env: flex  # Use the flexible environment for better memory/CPU control
entrypoint: gunicorn -w 4 -k gevent -t 120 --limit-request-line 8190 app:app

runtime_config:
  python_version: 3.12 # Use a recent, supported Python version

resources:
  # The embeddings model and FAISS index are memory-intensive.
  # Adjust instance class and memory based on your vector store size.
  # A standard index for a single PDF is fine on a small instance.
  cpu: 1
  memory_gb: 4
  disk_size_gb: 10

# Environment variables for the application
env_variables:
  # IMPORTANT: Replace <YOUR_GEMINI_API_KEY> with your actual API key value.
  GEMINI_API_KEY: "<YOUR_GEMINI_API_KEY>"
  # Other optional environment variables can be added here
